server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location ~* \.(js|css|html)$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        expires 0;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
