server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location ~* \.(js|css|html)$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        expires 0;
    }

    error_page 404 /pages/404.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
